import { Navbar } from "@/components/Navbar";
import { BottomNav } from "@/components/BottomNav";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { ShieldCheck, BookOpen, AlertTriangle, Phone } from "lucide-react";

const bettingRules = [
  { q: "Minimum / Maximum Bet", a: "Minimum bet amount is ₹100. Maximum bet varies per market and is displayed on the bet slip. Admin reserves the right to change limits." },
  { q: "Matched & Unmatched Bets", a: "Only matched bets are valid. Unmatched bets can be cancelled anytime. Once matched, bets cannot be cancelled or modified." },
  { q: "Fancy / Session Bets", a: "Fancy bets are settled based on official scores. If a session is incomplete due to rain or interruption, bets will be voided unless the result is already determined." },
  { q: "Live Match Rules", a: "In-play bets are accepted at the displayed odds. Any bet placed during downtime or technical glitch may be voided at admin's discretion." },
  { q: "Result Declaration", a: "Results are declared based on the official governing body of the respective sport. Any disputes must be raised within 24 hours." },
  { q: "Casino Rules", a: "All casino game results are generated by certified RNG systems. Minimum stake is ₹100. Results are final and binding." },
  { q: "Void Bets", a: "Bets may be voided if: match is abandoned, technical issues occur, suspicious activity is detected, or incorrect odds are offered." },
  { q: "Account Restrictions", a: "One account per person. Multiple accounts will be suspended. Admin reserves the right to block accounts involved in fraud or manipulation." },
];

const termsConditions = [
  { q: "Eligibility", a: "Users must be 18 years or older. By registering, you confirm you are of legal age to participate in online betting." },
  { q: "Account Security", a: "Users are responsible for keeping login credentials secure. The platform is not liable for unauthorized access due to user negligence." },
  { q: "Deposits & Withdrawals", a: "Deposits are processed instantly. Withdrawals are processed within 24 hours subject to verification. Minimum withdrawal is ₹500." },
  { q: "KYC Verification", a: "Users must complete KYC verification before first withdrawal. Required documents: Aadhar Card, PAN Card, and Bank Statement." },
  { q: "Liability", a: "The platform is not responsible for any losses incurred through betting. Users bet at their own risk and discretion." },
  { q: "Modification of Terms", a: "ROYAL BET reserves the right to modify these terms at any time. Continued use of the platform constitutes acceptance of updated terms." },
];

const responsibleGambling = [
  { q: "Set Your Limits", a: "Always set a budget before you start betting. Never bet more than you can afford to lose. Use our deposit limit feature to control spending." },
  { q: "Take Breaks", a: "Regular breaks help maintain a healthy relationship with betting. If you find yourself spending too much time, step away." },
  { q: "Recognize Problem Signs", a: "Warning signs include: chasing losses, borrowing money to bet, neglecting responsibilities, lying about betting activity, and feeling anxious about bets." },
  { q: "Self-Exclusion", a: "If you feel you need to take a break, contact support to temporarily or permanently exclude yourself from the platform." },
];

export default function Rules() {
  return (
    <div className="min-h-screen bg-background pb-16 md:pb-0">
      <Navbar />

      <div className="mx-auto max-w-3xl px-4 py-6 space-y-6">
        <h1 className="text-2xl font-bold text-foreground">Rules & Regulations</h1>

        {/* Betting Rules */}
        <section className="rounded-lg border border-border bg-card overflow-hidden">
          <div className="flex items-center gap-2 bg-primary px-4 py-3">
            <BookOpen className="h-5 w-5 text-primary-foreground" />
            <h2 className="font-display text-lg font-semibold text-primary-foreground">Betting Rules</h2>
          </div>
          <Accordion type="multiple" className="px-4">
            {bettingRules.map((r, i) => (
              <AccordionItem key={i} value={`bet-${i}`}>
                <AccordionTrigger className="text-sm font-medium text-foreground">{r.q}</AccordionTrigger>
                <AccordionContent className="text-sm text-muted-foreground">{r.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </section>

        {/* Terms & Conditions */}
        <section className="rounded-lg border border-border bg-card overflow-hidden">
          <div className="flex items-center gap-2 bg-accent px-4 py-3">
            <ShieldCheck className="h-5 w-5 text-accent-foreground" />
            <h2 className="font-display text-lg font-semibold text-accent-foreground">Terms & Conditions</h2>
          </div>
          <Accordion type="multiple" className="px-4">
            {termsConditions.map((r, i) => (
              <AccordionItem key={i} value={`tc-${i}`}>
                <AccordionTrigger className="text-sm font-medium text-foreground">{r.q}</AccordionTrigger>
                <AccordionContent className="text-sm text-muted-foreground">{r.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </section>

        {/* Responsible Gambling */}
        <section className="rounded-lg border border-border bg-card overflow-hidden">
          <div className="flex items-center gap-2 px-4 py-3" style={{ backgroundColor: "hsl(var(--live))" }}>
            <AlertTriangle className="h-5 w-5 text-primary-foreground" />
            <h2 className="font-display text-lg font-semibold text-primary-foreground">Responsible Gambling</h2>
          </div>
          <Accordion type="multiple" className="px-4">
            {responsibleGambling.map((r, i) => (
              <AccordionItem key={i} value={`rg-${i}`}>
                <AccordionTrigger className="text-sm font-medium text-foreground">{r.q}</AccordionTrigger>
                <AccordionContent className="text-sm text-muted-foreground">{r.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </section>

        {/* Help */}
        <div className="rounded-lg border border-border bg-card p-4 flex items-start gap-3">
          <Phone className="h-5 w-5 text-primary mt-0.5" />
          <div>
            <p className="text-sm font-semibold text-foreground">Need Help?</p>
            <p className="text-xs text-muted-foreground">Contact support via Telegram or WhatsApp for any queries regarding rules, bets or account issues.</p>
          </div>
        </div>
      </div>

      <BottomNav />
    </div>
  );
}
