/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SkyexchRouteImport } from './routes/skyexch'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InplayRouteImport } from './routes/inplay'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as BetHistoryRouteImport } from './routes/bet-history'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AnnaexchRouteImport } from './routes/annaexch'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyexchRoute = SkyexchRouteImport.update({
  id: '/skyexch',
  path: '/skyexch',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InplayRoute = InplayRouteImport.update({
  id: '/inplay',
  path: '/inplay',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const BetHistoryRoute = BetHistoryRouteImport.update({
  id: '/bet-history',
  path: '/bet-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnaexchRoute = AnnaexchRouteImport.update({
  id: '/annaexch',
  path: '/annaexch',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/annaexch': typeof AnnaexchRoute
  '/api-docs': typeof ApiDocsRoute
  '/bet-history': typeof BetHistoryRoute
  '/casino': typeof CasinoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/inplay': typeof InplayRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/skyexch': typeof SkyexchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/annaexch': typeof AnnaexchRoute
  '/api-docs': typeof ApiDocsRoute
  '/bet-history': typeof BetHistoryRoute
  '/casino': typeof CasinoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/inplay': typeof InplayRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/skyexch': typeof SkyexchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/annaexch': typeof AnnaexchRoute
  '/api-docs': typeof ApiDocsRoute
  '/bet-history': typeof BetHistoryRoute
  '/casino': typeof CasinoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/inplay': typeof InplayRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/skyexch': typeof SkyexchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agent'
    | '/annaexch'
    | '/api-docs'
    | '/bet-history'
    | '/casino'
    | '/forgot-password'
    | '/history'
    | '/inplay'
    | '/login'
    | '/play'
    | '/privacy'
    | '/reset-password'
    | '/responsible-gaming'
    | '/rules'
    | '/signup'
    | '/skyexch'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agent'
    | '/annaexch'
    | '/api-docs'
    | '/bet-history'
    | '/casino'
    | '/forgot-password'
    | '/history'
    | '/inplay'
    | '/login'
    | '/play'
    | '/privacy'
    | '/reset-password'
    | '/responsible-gaming'
    | '/rules'
    | '/signup'
    | '/skyexch'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/agent'
    | '/annaexch'
    | '/api-docs'
    | '/bet-history'
    | '/casino'
    | '/forgot-password'
    | '/history'
    | '/inplay'
    | '/login'
    | '/play'
    | '/privacy'
    | '/reset-password'
    | '/responsible-gaming'
    | '/rules'
    | '/signup'
    | '/skyexch'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  AnnaexchRoute: typeof AnnaexchRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BetHistoryRoute: typeof BetHistoryRoute
  CasinoRoute: typeof CasinoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  InplayRoute: typeof InplayRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  RulesRoute: typeof RulesRoute
  SignupRoute: typeof SignupRoute
  SkyexchRoute: typeof SkyexchRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skyexch': {
      id: '/skyexch'
      path: '/skyexch'
      fullPath: '/skyexch'
      preLoaderRoute: typeof SkyexchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inplay': {
      id: '/inplay'
      path: '/inplay'
      fullPath: '/inplay'
      preLoaderRoute: typeof InplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-history': {
      id: '/bet-history'
      path: '/bet-history'
      fullPath: '/bet-history'
      preLoaderRoute: typeof BetHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annaexch': {
      id: '/annaexch'
      path: '/annaexch'
      fullPath: '/annaexch'
      preLoaderRoute: typeof AnnaexchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  AnnaexchRoute: AnnaexchRoute,
  ApiDocsRoute: ApiDocsRoute,
  BetHistoryRoute: BetHistoryRoute,
  CasinoRoute: CasinoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  InplayRoute: InplayRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  RulesRoute: RulesRoute,
  SignupRoute: SignupRoute,
  SkyexchRoute: SkyexchRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
